name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2

    - name: install tools
      run: sudo apt-get install xz-utils

    - name: Install dependencies
      uses: subosito/flutter-action@v1.4.0
      working-directory: sledilnik_mobile_app
      run: flutter pub get

    - name: Run tests
      uses: subosito/flutter-action@v1.4.0
      working-directory: sledilnik_mobile_app
      run: flutter test
