name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.4.0

    - name: Install dependencies
      working-directory: sledilnik_mobile_app
      run: flutter pub get

    - name: Build Android APK
      working-directory: sledilnik_mobile_app
      run: flutter build apk

    - name: Build Android app bundle
      working-directory: sledilnik_mobile_app
      run: flutter build appbundle

    - name: Build iOS app
      working-directory: sledilnik_mobile_app
      run: flutter build ios

    - name: Run tests
      working-directory: sledilnik_mobile_app
      run: flutter test
