name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.4.0

    - name: Install dependencies
      working-directory: sledilnik_mobile_app
      run: flutter pub get

    #- name: Run tests
    #  working-directory: sledilnik_mobile_app
    #  run: flutter test

    - name: Build Android APK
      working-directory: sledilnik_mobile_app
      run: |
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        flutter build apk
        ls -la `find . -type f -name "*.apk"`

    - name: Build Android app bundle
      working-directory: sledilnik_mobile_app
      run: flutter build appbundle

    #- name: Build iOS app
    #  working-directory: sledilnik_mobile_app
    #  run: flutter build ios

    - name: Upload artifact - app-release.apk
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: sledilnik_mobile_app/build/app/outputs/apk/release/app-release.apk

    - name: Upload artifact - app-arm64-v8a-release.apk
      uses: actions/upload-artifact@v2
      with:
        name: app-arm64-v8a-release.apk
        path: sledilnik_mobile_app/build/app/outputs/apk/release/app-arm64-v8a-release.apk

    - name: Upload artifact - app-armeabi-v7a-release.apk
      uses: actions/upload-artifact@v2
      with:
        name: app-armeabi-v7a-release.apk
        path: sledilnik_mobile_app/build/app/outputs/apk/release/app-armeabi-v7a-release.apk

    - name: Upload artifact - app-x86_64-release.apk
      uses: actions/upload-artifact@v2
      with:
        name: app-x86_64-release.apk
        path: sledilnik_mobile_app/build/app/outputs/apk/release/app-x86_64-release.apk
